// Copyright 2017 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_ota_control                     19
#define gattdb_xfader_setting                  22
#define gattdb_ifader_setting                  24
#define gattdb_line_phono_switch               26
#define gattdb_input_gain                      28
#define gattdb_eq_hi                           30
#define gattdb_eq_mid                          32
#define gattdb_eq_low                          34
#define gattdb_input_fader                     36
#define gattdb_cross_fader                     38
#define gattdb_master_booth_gain               41
#define gattdb_monitor_level_select            43

#endif
